name: 🚀 Deploy Ryxo App
on: push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP without any shared extensions except mbstring
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: none, mbstring

      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Rename public folder to public_html
        run: mv public public_html

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5 # Use an FTP deployment action
        with:
          server: files.000webhost.com
          port: 21
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # local-dir: 'public' # Change this to the directory containing your Laravel app
          # server-dir: '/public_html/' # Change this to the directory on your server where you want to deploy
